sudo: required
language: node_js
node_js:
- '6.9'
env:
  global:
  - secure: Np51tSdnV3SxOJBThlVOfFBStp+P4k3D5L5towdfPVzOOikm9OvVdskhCXvcCEU1e9Ww/gZIFCloqzfIZVxogJmFztPUzG6MsE1MzADAhy1HqMRbZT2xKU3YLcpqENsGwEznNFu1ToiS04pNPuMCsVP0Wl6DuA42KhXjVi8IjhPsshzx+WdBhl1TpXKtNQlQuT/wjkCQB61TrAU+yEb1TRTpCGjiZ5Py3e6nCp7zCqB5rHuy0j13xR3YIgZ4yxXEydsO1el1c8qxlKQX1RqQo3bCIBP7ybVzblODWPmwG29Z4IPWWsJGEBVR1/aFcyILpznU0jNfdLhC6pRj1RC147pK3DVPo18PHobNJlG1DSXnJdLYkbJI4HYxkjju9boov4ye/BK3XCJKA0MGTP0rESXlGBYOVMXxGubKkkpLNiD7DpnWVOCSExFmEKSvB4DIwtAexp6Vi/R/7maKl3k9kz8Gio6rElyid7vRocCKVe/YsACTs5OkWKiPF5mEkQJYt1ihAsJou204jUA4zFsoN7kJo7aOXFRyrPYBHlCx/eCVowdjS6HokZSQ6enQr1gJ5OaOtNJSmZ74Ya0ggwqrnPEL/aaewUDdhuxlAyg5pnt/AHnJvYuXuBu8icKbyLRbklekSRP7K6QqJlLnLgN25gsLsvYLKj1Kh7GwN8OjQ8k=
  - secure: nDj9gmWWcP/Zxso6I5Sc7UYj3cV3yQ/iil5dEWLTd01f3rpKnlqGqvG+pTADu8oiH5SXAW8NvtnwGzdTruNauyKb2zzHJK+codt8mkTCbUkBwiFrYEieXO6Lwl+ZU/P7eeiJ8bObf9tAM4n4ysiNDA6KgXwGTjP0xvIxwhpF+/T9llZNYk5csTuxb6+MccwI1uJwQwyg5qAUBCh4F6wcRDNcO3AzQ466PSqCDZaHJHolFK886iPNlTV6GyaEtU3hK6STuKRbDiOqlyjQ82+XyURJIW5/FYxaXXBFZVdSF389Egd7jnAJtd81lChExb/ORX+chLSOVGUG2n0kd2e3buT0Kyvsik7IFsMXytjCivcS8Z2hGjNnfDslJTPzw+5VKSYlAQc8Ff1HnnqBEGe3jP7YDt8xbE6KlUx8ZHswGAiuJZMvCZqlh0OHma2GOK7cZW82pCKwjaMDQs68pITxTlSV/NCpEyeaMqckYQj2ZcPvsxIG8X6NWjkeUphD6LPDQO/ZHlscRAUtvMRTSV4JvSIQytShpYuBQoJH6YdbEWuTlrPIOMt+gmOBrMdgNVmvlbgCg/vGzyXvnjzO+GLetasOdgqNPY9PWBAE2hZi6SBWvlaA9q7uKwocwXBzu2h8U5WATBdWn/e09NHh+OyEIwZWgUqRDictAu0q5OjXejw=
services:
- docker
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --env=prod
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t $DOCKER_USER/college-app-tracker-ui .
- docker tag $DOCKER_USER/college-app-tracker-ui $DOCKER_USER/college-app-tracker-ui:latest
- docker push $DOCKER_USER/college-app-tracker-ui
notifications:
  email:
    on_failure: change
    on_success: change
